#!/bin/sh

SOURCE=fit_trajectory.cxx
EXE=exeDD

if [ "$1" ]
then
 SOURCE="$1"
 EXE="$1.exe"
fi

echo compiling $EXE
rm -f $EXE *.o

gcc -o $EXE.o -c $SOURCE `root-config --cflags`
gcc -o $EXE $EXE.o `root-config --cflags` `root-config --libs` -L$ROOTSYS/lib `gsl-config --libs` -lMinuit -lMathMore -lstdc++

echo running $EXE 
./$EXE 